In [1]:
# Understanding EV Adoption
#A Data-Driven Analysis of Range Anxiety and Consumer Purchase Decisions

## Data Profiling
### Objectivey

#The objective of this notebook is to understand the structure, quality, and completeness of the consumer survey dataset before performing any data cleaning or analysis.

In [18]:
## Import Libraries
import pandas as pd
import numpy as np

In [3]:
## Load Dataset

df = pd.read_excel("../data/raw/EV_Adoption_and_Range_Anxiety_Dataset.xlsx")

NameError: name 'pd' is not defined

In [2]:
## Dataset Overview
df.head()
df.shape
df.columns()

NameError: name 'df' is not defined

In [ ]:
## Data Types
df.info()

In [ ]:
## Missing Values

In [ ]:
## Duplicate Records

In [ ]:
## Initial Observations

In [9]:
import os

print(os.getcwd())

c:\Users\Lakshman\Desktop\project\eda

In [10]:
import os

print(os.listdir())

['01_Data_Profiling.ipynb']

In [11]:
import os

print(os.listdir(".."))

['Data Quality Checklist.docx', 'eda', 'EV_Adoption_and_Range_Anxiety_Dataset.csv', 'EV_Adoption_and_Range_Anxiety_Dataset.xlsx']

In [12]:
import os

print(os.listdir("../data/raw"))

['EV_Adoption_and_Range_Anxiety_Dataset.xlsx']

In [3]:
import pandas as pd

df = pd.read_excel("../data/raw/EV_Adoption_and_Range_Anxiety_Dataset.xlsx")

df.head()

,Buyer_ID,Age,Gender,Annual_Income_USD,City_Type,Daily_Commute_km,Number_of_Cars_Owned,Current_Car_Type,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Home_Charging_Possible,Environmental_Concern_Level,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,EV00001,56,Male,44906.0,Rural,18.1,1,Truck,1,0,Yes,4.0,Yes,Low,No
1,EV00002,36,Male,88754.0,Rural,5.0,1,SUV,2,3,Yes,1.0,Yes,Low,No
2,EV00003,42,Male,155958.0,Urban,32.2,2,Sedan,14,3,No,2.0,Yes,Medium,Yes
3,EV00004,31,Male,37059.0,Rural,89.9,1,Sedan,2,1,Yes,4.0,No,Low,No
4,EV00005,48,Female,48552.0,Rural,71.0,1,Sedan,2,0,Yes,3.0,Yes,Low,No

In [14]:
print(os.listdir("../data/raw"))

['EV_Adoption_and_Range_Anxiety_Dataset.xlsx']

In [4]:
df.shape

(10000, 15)

In [5]:
### Observation

#The dataset contains ______ rows and ______ columns, indicating that it is sufficiently large for meaningful exploratory analysis and predictive modeling.

In [17]:
df.columns

Index(['Buyer_ID', 'Age', 'Gender', 'Annual_Income_USD', 'City_Type',
       'Daily_Commute_km', 'Number_of_Cars_Owned', 'Current_Car_Type',
       'Charging_Stations_Near_Home', 'Charging_Stations_Near_Work',
       'Home_Charging_Possible', 'Environmental_Concern_Level',
       'Subsidy_Available', 'Range_Anxiety_Level', 'Will_Buy_EV'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Buyer_ID                     10000 non-null  str
 1   Age                          10000 non-null  int64
 2   Gender                       10000 non-null  str
 3   Annual_Income_USD            9822 non-null   float64
 4   City_Type                    10000 non-null  str
 5   Daily_Commute_km             9819 non-null   float64
 6   Number_of_Cars_Owned         10000 non-null  int64
 7   Current_Car_Type             10000 non-null  str
 8   Charging_Stations_Near_Home  10000 non-null  int64
 9   Charging_Stations_Near_Work  10000 non-null  int64
 10  Home_Charging_Possible       10000 non-null  str
 11  Environmental_Concern_Level  9816 non-null   float64
 12  Subsidy_Available            10000 non-null  str
 13  Range_Anxiety_Level          10000 non-null  str
 14  Will_Buy_EV                  10000 non-null  str
dtypes: float64(3), int64(4), str(8)
memory usage: 1.1 MB

In [19]:
df.describe()

,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level
count,10000.000000,9822.000000,9819.000000,10000.000000,10000.000000,10000.000000,9816.000000
mean,46.936200,85378.485848,41.105418,1.859900,5.346900,7.458200,2.982783
std,12.945968,32838.684167,23.351276,0.855421,4.049074,5.259374,1.413784
min,25.000000,30000.000000,5.000000,1.000000,0.000000,0.000000,1.000000
25%,36.000000,61369.500000,23.250000,1.000000,2.000000,3.000000,2.000000
50%,47.000000,84708.000000,40.200000,2.000000,5.000000,6.000000,3.000000
75%,58.000000,107383.250000,57.000000,2.000000,8.000000,11.000000,4.000000
max,69.000000,223345.000000,135.500000,4.000000,14.000000,19.000000,5.000000

In [15]:
df.isnull().sum()

Buyer_ID                         0
Age                              0
Gender                           0
Annual_Income_USD              178
City_Type                        0
Daily_Commute_km               181
Number_of_Cars_Owned             0
Current_Car_Type                 0
Charging_Stations_Near_Home      0
Charging_Stations_Near_Work      0
Home_Charging_Possible           0
Environmental_Concern_Level    184
Subsidy_Available                0
Range_Anxiety_Level              0
Will_Buy_EV                      0
dtype: int64

In [ ]:
## Initial Data Quality Assessment

#Observations:

#- Dataset contains  178+181+184 missing values.
#- Missing values are present in 3 columns.
#- No action has been taken yet because profiling should precede cleaning.

In [14]:
df["Will_Buy_EV"].value_counts()

Will_Buy_EV
No     8250
Yes    1750
Name: count, dtype: int64

In [13]:
df["Range_Anxiety_Level"].value_counts()

Range_Anxiety_Level
Low       8310
Medium    1523
High       167
Name: count, dtype: int64

In [12]:
pd.crosstab(df["Range_Anxiety_Level"], df["Will_Buy_EV"])
#relation between two columns

Will_Buy_EV            No   Yes
Range_Anxiety_Level
High                  166     1
Low                  6659  1651
Medium               1425    98

In [10]:
pd.crosstab(
    df["Range_Anxiety_Level"],
    df["Will_Buy_EV"],
    normalize="index"
) * 100

Will_Buy_EV                 No        Yes
Range_Anxiety_Level
High                 99.401198   0.598802
Low                  80.132371  19.867629
Medium               93.565332   6.434668

In [11]:
pd.crosstab(
    df["Home_Charging_Possible"],
    df["Will_Buy_EV"],
    normalize="index"
) * 100

Will_Buy_EV                    No        Yes
Home_Charging_Possible
No                      86.630180  13.369820
Yes                     79.928606  20.071394

In [7]:
pd.crosstab(
    df["Environmental_Concern_Level"],
    df["Will_Buy_EV"],
    normalize="index"
) * 100

Will_Buy_EV                         No        Yes
Environmental_Concern_Level
1.0                          97.863885   2.136115
2.0                          95.071869   4.928131
3.0                          85.546476  14.453524
4.0                          74.710910  25.289090
5.0                          58.595388  41.404612

In [16]:
df["Annual_Income_USD"].describe()

count      9822.000000
mean      85378.485848
std       32838.684167
min       30000.000000
25%       61369.500000
50%       84708.000000
75%      107383.250000
max      223345.000000
Name: Annual_Income_USD, dtype: float64

In [19]:
df["Annual_Income_USD"].isnull().sum()

np.int64(178)

In [20]:
df["Income_Group"] = pd.qcut(
    df["Annual_Income_USD"],
    q=4,
    labels=["Low", "Middle", "Upper Middle", "High"]
)

In [21]:
pd.crosstab(
    df["Income_Group"],
    df["Will_Buy_EV"],
    normalize="index"
) * 100

Will_Buy_EV          No        Yes
Income_Group
Low           90.472313   9.527687
Middle        85.824847  14.175153
Upper Middle  80.488798  19.511202
High          73.778502  26.221498

In [22]:
bins = [20, 30, 40, 50, 60, 70]
labels = ["20-29", "30-39", "40-49", "50-59", "60-69"]

df["Age_Group"] = pd.cut(df["Age"], bins=bins, labels=labels, right=False)

In [23]:
pd.crosstab(
    df["Age_Group"],
    df["Will_Buy_EV"],
    normalize="index"
) * 100

Will_Buy_EV         No        Yes
Age_Group
20-29        82.479784  17.520216
30-39        82.935615  17.064385
40-49        83.018038  16.981962
50-59        80.527753  19.472247
60-69        83.507973  16.492027

In [24]:
pd.crosstab(
    df["Subsidy_Available"],
    df["Will_Buy_EV"],
    normalize="index"
) * 100

Will_Buy_EV               No        Yes
Subsidy_Available
No                 97.469940   2.530060
Yes                72.553262  27.446738